app/controllers/user/cart_items_controller.rb
app/controllers/user/deliveries_controller.rb
app/controllers/user/orders_controller.rb
app/controllers/user/products_controller.rb
app/controllers/user/users_controller.rb

[Add]controllers/user

---

app/controllers/admin/admins_controller.rb
app/controllers/admin/genres_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/admin/products_controller.rb
app/controllers/admin/users_controller.rb

[edit] controllers/admin

---

config/routes.rb

▼ルーティングエラーの修正(原因)
・rootの記述修正
・resourcesの後にonlyの書き忘れ。

[Update] routing

---

config/routes.rb

[Fix] routing

---

app/models/cart_item.rb
app/models/delivery.rb
app/models/genre.rb
app/models/order.rb
app/models/order_item.rb
app/models/product.rb
app/models/user.rb
db/migrate/20200402074625_create_products.rb
db/migrate/20200402080643_create_genres.rb
db/migrate/20200402080828_create_orders.rb
db/migrate/20200402081056_create_deliveries.rb
db/migrate/20200402081527_create_cart_items.rb
db/migrate/20200402083122_devise_create_admins.rb
db/migrate/20200402084333_create_order_items.rb
db/schema.rb
test/fixtures/admins.yml
test/fixtures/cart_items.yml
test/fixtures/deliveries.yml
test/fixtures/genres.yml
test/fixtures/order_items.yml
test/fixtures/orders.yml
test/fixtures/products.yml
test/models/admin_test.rb
test/models/cart_item_test.rb
test/models/delivery_test.rb
test/models/genre_test.rb
test/models/order_item_test.rb
test/models/order_test.rb
test/models/product_test.rb

[Add] models and tables

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss

[edit] application.js

---

db/migrate/20200402074625_create_products.rb
db/schema.rb

[Fix] schema

---

app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb

[edit]stylesheets and sass

---

app/controllers/admin/users_controller.rb
app/controllers/user/users_controller.rb
app/views/user/users/edit.html.erb
app/views/user/users/show.html.erb

controllers/user/users_controllersを追加
views/usersを追加

[Add]controllers,views

---

app/controllers/admin/users_controller.rb
app/controllers/user/users_controller.rb
app/models/user.rb
app/views/admin/users/edit.html.erb
app/views/admin/users/index.html.erb
app/views/admin/users/show.html.erb
app/views/user/users/confirm.html.erb
app/views/user/users/edit.html.erb
app/views/user/users/show.html.erb
app/views/user/users/top.html.erb

user controller/users
admin controller/users
user_model
admin view/users
user view/users
の追加、修正

[Add,Fix]admin,user_controller,models,admin,user_view

---

app/views/layouts/application.html.erb
app/views/users/registrations/new.html.erb
config/routes.rb

[edit] user/registrations.new.html

---

app/assets/stylesheets/user/deliveries.scss
app/controllers/user/deliveries_controller.rb
app/models/delivery.rb
app/views/user/deliveries/edit.html.erb
app/views/user/deliveries/index.html.erb

[Add] delivery

---

app/controllers/admin/users_controller.rb
app/controllers/user/users_controller.rb
app/models/user.rb
app/views/admin/users/edit.html.erb
app/views/admin/users/index.html.erb
app/views/admin/users/show.html.erb
app/views/user/users/confirm.html.erb
app/views/user/users/edit.html.erb
app/views/user/users/show.html.erb

user,admin/controller
user/model
user,admin/view
修正しました。

[FIX]user_admin,controller,model,view

---

app/assets/stylesheets/admin/products.scss
app/assets/stylesheets/user/orders.scss
app/assets/stylesheets/user/products.scss
app/controllers/admin/products_controller.rb
app/controllers/user/deliveries_controller.rb
app/controllers/user/orders_controller.rb
app/controllers/user/products_controller.rb
app/models/delivery.rb
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb
app/views/admin/products/edit.html.erb
app/views/admin/products/index.html.erb
app/views/admin/products/new.html.erb
app/views/admin/products/show.html.erb
app/views/user/deliveries/edit.html.erb
app/views/user/deliveries/index.html.erb
app/views/user/orders/confirm.html.erb
app/views/user/orders/new.html.erb
app/views/user/orders/thanks.html.erb
app/views/user/products/index.html.erb
config/routes.rb
db/migrate/20200402080828_create_orders.rb

・orderのnew,confirm,thanksのcontroller,viewの作成。
・product,genre,deliveryのview微調整

[Add] orders_new&confirm&thanks

---

config/routes.rb

[edit]routes/rb

---

app/views/admin/products/index.html.erb

管理者側商品一覧ページに新規商品登録ボタン(プラスボタン)追加

[Add] product-create-button

---

app/views/user/cart_items/index.html.erb

カート機能の細かい部分を直しました
-　「カートの数量」の箇所
- 「情報入力に進む」の箇所

[Fix] CartItem Function modify

---

app/models/user.rb
app/views/admin/users/edit.html.erb
app/views/admin/users/show.html.erb
app/views/user/users/edit.html.erb

model/user.rb
エラーメッセージの追加
user/viewの細かいところの修正

[Add,Fix]model,admin/user_view

---

app/controllers/user/orders_controller.rb
app/views/user/orders/confirm.html.erb
db/migrate/20200402084333_create_order_items.rb
db/schema.rb

app/controllers/user/orders_controller.rb  →createアクション(購入確定時)でorder_itemsのレコードが作成されるようにコントローラーにコード追加。
app/views/user/orders/confirm.html.erb →form_forの場所変えただけ。
db/migrate/20200402084333_create_order_items.rb →production_statusにデフォルトで0(着手不可)設定。

[Add] order_items(create)

---

app/views/user/users/show.html.erb

[Fix]views/user/users/show

---

app/controllers/admin/orders_controller.rb
app/models/order.rb
app/models/order_item.rb
app/views/user/users/top.html.erb

[create] admin/order/index&show

---

app/controllers/user/deliveries_controller.rb

before_actionの追加
editアクションのrender先の変更

[Fix] deliveries_controller

---

app/controllers/user/cart_items_controller.rb
app/controllers/user/orders_controller.rb
app/views/user/orders/index.html.erb
app/views/user/orders/show.html.erb
app/views/user/products/show.html.erb
db/schema.rb

以下を追加と修正しました：
-カート機能を修正し、細かいところを直しました
-ユーザー側の注文履歴（一覧と詳細）を追加しました

[Modify] CartItem Functions, [Add] User's order history(index and show)

---

app/views/layouts/application.html.erb

[edit] layouts

---

app/views/admin/orders/index.html.erb

[add] orders/index.html

---

app/controllers/admin/products_controller.rb
app/controllers/user/users_controller.rb

user_controllerのbaria_userにconfirm追加
productの商品作成後のリダイレクト先変更

[Fix] user&product_controller

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/jquery.jpostal.js
app/controllers/user/cart_items_controller.rb
app/controllers/user/users_controller.rb
app/controllers/users/registrations_controller.rb
app/mailers/thanks_mailer.rb
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb
app/views/admin/products/edit.html.erb
app/views/admin/products/index.html.erb
app/views/admin/products/new.html.erb
app/views/admin/products/show.html.erb
app/views/layouts/_errors.html.erb
app/views/thanks_mailer/send_confirm_to_user.text.erb
app/views/user/cart_items/_cart_items.html.erb
app/views/user/cart_items/destroy.js.erb
app/views/user/cart_items/index.html.erb
app/views/user/cart_items/update.js.erb
app/views/user/deliveries/edit.html.erb
app/views/user/deliveries/index.html.erb
app/views/user/orders/confirm.html.erb
app/views/user/orders/new.html.erb
app/views/user/users/about.html.erb
config/environments/development.rb
config/routes.rb
test/mailers/previews/thanks_mailer_preview.rb
test/mailers/thanks_mailer_test.rb

※住所の自動入力の追加
※Google Mapのとこ、コントローラーに@map_addressを定義して、ビューの住所とmapのピンが一致するように調整 。
※カート機能にajax(非同期通信追加)

[Add] address_autofill/[Fix] Google_map/[Add] ajax_cart_items

---

app/controllers/admins/sessions_controller.rb
app/controllers/user/products_controller.rb
app/views/admin/orders/index.html.erb
app/views/layouts/admin.html.erb
app/views/layouts/application.html.erb
app/views/user/products/index.html.erb
app/views/user/users/top.html.erb
config/application.rb
config/locales/ja.yml

[edit] admin/session/layout&admin/order/index and more

---

app/assets/stylesheets/application.scss
app/views/admin/products/index.html.erb
app/views/admin/products/show.html.erb
app/views/user/products/index.html.erb

[Fix] admin/products/show

---

app/controllers/user/cart_items_controller.rb
app/views/user/orders/index.html.erb
app/views/user/orders/show.html.erb
config/application.rb
config/locales/ja.yml

以下を追加・修正しました
- カート機能において、同じ商品を2回カートに入れたとき、一つの行にまとまり、個数だけ足される様にしました。
- 日時の設定を追加、変更しました

[fix]cart item functions, [modify]date/time settings

---

app/views/user/cart_items/_cart_items.html.erb
app/views/user/cart_items/index.html.erb

[Fix] cart_items/index_ajax

---

app/controllers/user/products_controller.rb
app/views/layouts/application.html.erb
app/views/user/cart_items/_cart_items.html.erb
app/views/user/cart_items/index.html.erb

[Fix] user/products/index

---

app/views/user/orders/confirm.html.erb
app/views/user/orders/new.html.erb
config/initializers/kaminari_config.rb

たくさんコード変更してあるように見えるけど、先頭に<div class="container>を足しただけです。(container-fluidだとpaddingが機能してなかったので足しました。)

[Fix] order_views

---

.gitignore
app/views/user/cart_items/_cart_items.html.erb
app/views/user/cart_items/index.html.erb
app/views/user/orders/index.html.erb
app/views/user/orders/show.html.erb

以下を修正、追加しました
ー　カート機能のレイアウト
ー　注文履歴一覧のレイアウト
ー　gitignoreファイルに内容を追加

[fix]cart item layout, [fix] order(index and show) layout

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/user/products.scss
app/views/admin/products/show.html.erb
app/views/admins/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/user/products/_sidebar.html.erb
app/views/user/products/index.html.erb
app/views/user/products/show.html.erb
app/views/user/users/top.html.erb
app/views/users/registrations/new.html.erb
app/views/users/sessions/new.html.erb
app/views/users/shared/_links.html.erb

[edit] view

---

app/views/admin/orders/show.html.erb
app/views/admin/users/show.html.erb

admin/orders/show、admin/users/showのviewを微調整

[Fix] admin/views
